[versions]

agp = "9.0.0"
androidx-activity = "1.12.3"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
androidx-navigation = "2.9.1"
androidx-room = "2.8.4"
androidx-sqlite = "2.6.2"
appdirs = "1.5.0"

caupain = "1.8.1"
compose-kmp = "1.10.0"

junit = "4.13.2"

kotlin = "2.3.10"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
ksp = "2.3.5"

material = "1.13.0"
material3 = "1.9.0"
materialIcons = "1.7.3"
metro = "0.10.2"

[libraries]

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-sqlite = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidx-sqlite" }
appdirs = { module = "net.harawata:appdirs", version.ref = "appdirs" }

compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-kmp" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-kmp" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-kmp" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-kmp" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-kmp" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-kmp" }

junit = { module = "junit:junit", version.ref = "junit" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIcons" }
metrox-viewmodel-compose = { module = "dev.zacsweers.metro:metrox-viewmodel-compose", version.ref = "metro" }

[plugins]

androidApplication = { id = "com.android.application", version.ref = "agp" }
androidKmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }

caupain = { id = "com.deezer.caupain", version.ref = "caupain" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-kmp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
